theme = "catppuccin_mocha"

[editor]
line-number = "relative"
color-modes = true
true-color = true
auto-completion = true
continue-comments = false
cursorline = true
completion-timeout = 5

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
C-A-p = ":sh python3 %{buffer_name}"
C-A-g = ":sh go run %{buffer_name}"
C-A-z = ":sh zig run %{buffer_name}"
S-w = ":w"
S-q = ":q"

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.file-picker]
hidden = false
ignore = true

[keys.normal.space]
f = "file_picker_in_current_directory"
